server:
  path: "/Users/aroslavbudancev/Documents/Projects/NifiServer/mcp-nifi/src/nifi_server.py"
  cwd: "/Users/aroslavbudancev/Documents/Projects/NifiServer/mcp-nifi/"
  name: "nifi"
  server_name: "nifi"
checkpointer:
  url: "postgresql://agent:agent_pass@localhost:5434/agent_storage"
llm:
  name: Qwen/Qwen3-235B-A22B-Instruct-2507-tput
  base_url: "https://api.together.xyz/v1/"
  temperature: 0.0
  top_p: 0.1
